# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Description of what the lane does"
  lane :build do
    build_mac_app(
      workspace: "MetaX.xcworkspace",
      configuration: "Release",
      scheme: "MetaX",
      silent: true,
      clean: true,
      output_directory: "./build", # Destination directory. Defaults to current directory.
      output_name: "MetaX.pkg",       # specify the name of the .ipa file to generate (including file extension)
      export_method: "development"
    )
  end
end
